import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about/about";
import Experience from "../components/experience/experience";
import Header from "../components/header/header";
import Hero from "../components/hero/hero";

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] h-screen text-white snap-y snap-mandatory  overflow-scroll z-0">
      <Head>
        <title>Alvin Portfolio</title>
        <meta
          name="description"
          content="Generated by Alvin supported by nextjs"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* headers */}
      <Header />
      {/* hero */}
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      {/* about */}
      <section id="about" className="snap-center">
        <About />
      </section>
      {/* exprience */}
      <section id="experience" className="snap-center">
        <Experience />
      </section>
    </div>
  );
};

export default Home;
