import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about/about";
import Experience from "../components/experience/experience";
import Header from "../components/header/header";
import Hero from "../components/hero/hero";
import Project from "../components/project/project";
import Skills from "../components/skill/skills";

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] h-screen text-white snap-y snap-mandatory  overflow-scroll overflow-x-hidden z-0 scroll-auto scrollbar-w-1 scrollbar-thumb-lime-300 scrollbar-track-slate-900">
      <Head>
        <title>Alvin Portfolio</title>
        <meta
          name="description"
          content="Generated by Alvin supported by nextjs"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* headers */}
      <Header />
      {/* hero */}
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      {/* about */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* exprience */}
      <section id="experience" className="snap-center">
        <Experience />
      </section>

      {/* skills */}
      <section id="skills" className="snap-start">
        <Skills />
      </section>

      {/* projects */}
      <section id="project" className="snap-start">
        <Project />
      </section>
    </div>
  );
};

export default Home;
